name: app_environment
channels:
  - snowflake
dependencies:
  - python=3.11.*
  - snowflake-ml-python=1.7.4
  - snowflake-snowpark-python=
  - streamlit=
  - tabulate=0.9.0
  - trulens-connectors-snowflake=1.2.4
  - trulens-core=1.2.4
  - trulens-feedback=1.2.11
  - trulens-providers-cortex=1.2.4
